apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-hpa
  namespace: devops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploy-todolist
  minReplicas: 1
  maxReplicas: 5 # Ou o número máximo de pods desejado
  targetCPUUtilizationPercentage: 50 # Utilização desejada (50% de uso de CPU)
