apiVersion: v1
kind: Service
metadata:
  name: svc-todolist
  namespace: devops
spec:
  selector:
    app: deploy-todolist
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
